django-ledger/dev_env/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django_ledger.urls', namespace='django_ledger')),
]

try:
    # checking for graphene_django installation to provide and enable graphql services...
    from graphene_django.views import GraphQLView
    from django_ledger.contrib.django_ledger_graphql.api import schema

    urlpatterns += [
        path('graphql/', csrf_exempt(GraphQLView.as_view(graphiql=True, schema=schema)))
    ]
except ImportError:
    pass

django-ledger/django_ledger/models/accounts.py
"""
Django Ledger created by Miguel Sanda <msanda@arrobalytics.com>.
Copyright© EDMA Group Inc licensed under the GPLv3 Agreement.

Contributions to this module:
Miguel Sanda <msanda@arrobalytics.com>
"""
from typing import Union
from uuid import uuid4

from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Q
from django.utils.translation import gettext_lazy as _

from django_ledger.io.roles import ACCOUNT_ROLES, BS_ROLES, GROUP_INVOICE, GROUP_BILL
from django_ledger.models.mixins import CreateUpdateMixIn, ParentChildMixIn

DEBIT = 'debit'
CREDIT = 'credit'


class AccountModelQuerySet(models.QuerySet):

    def active(self):
        return self.filter(active=True)

    def with_roles(self, roles: Union[list, str]):
        if isinstance(roles, str):
            roles = [roles]
        return self.filter(role__in=roles)


class AccountModelManager(models.Manager):

    def get_queryset(self):
        return AccountModelQuerySet(self.model, using=self._db)

    def for_entity(self, user_model, entity_slug: str, coa_slug: str = None):
        qs = self.get_queryset()
        qs = qs.filter(
            Q(coa__entity__slug__exact=entity_slug) &
            (
                    Q(coa__entity__admin=user_model) |
                    Q(coa__entity__managers__in=[user_model])
            )
        ).order_by('code')
        if coa_slug:
            qs = qs.filter(coa__slug__iexact=coa_slug)
        return qs

    def with_roles(self, roles: Union[list, str], entity_slug: str, user_model):
        if isinstance(roles, str):
            roles = [roles]
        qs = self.for_entity(entity_slug=entity_slug, user_model=user_model)
        return qs.filter(role__in=roles)

    def with_roles_available(self, roles: Union[list, str], entity_slug: str, user_model):
        if isinstance(roles, str):
            roles = [roles]
        qs = self.for_entity_available(entity_slug=entity_slug, user_model=user_model)
        return qs.filter(role__in=roles)

    def for_entity_available(self, user_model, entity_slug: str, coa_slug: str = None):
        qs = self.for_entity(
            user_model=user_model,
            entity_slug=entity_slug,
            coa_slug=coa_slug)
        return qs.filter(
            active=True,
            locked=False
        )

    def for_invoice(self, user_model, entity_slug: str, coa_slug: str = None):
        qs = self.for_entity_available(
            user_model=user_model,
            entity_slug=entity_slug,
            coa_slug=coa_slug)
        return qs.filter(role__in=GROUP_INVOICE)

    def for_bill(self, user_model, entity_slug: str, coa_slug: str = None):
        qs = self.for_entity_available(
            user_model=user_model,
            entity_slug=entity_slug,
            coa_slug=coa_slug)
        return qs.filter(role__in=GROUP_BILL)


class AccountModelAbstract(ParentChildMixIn, CreateUpdateMixIn):
    """
    Djetler's Base Account Model Abstract
    """
    BALANCE_TYPE = [
        (CREDIT, _('Credit')),
        (DEBIT, _('Debit'))
    ]

    uuid = models.UUIDField(default=uuid4, editable=False, primary_key=True)
    code = models.CharField(max_length=10, verbose_name=_('Account Code'))
    name = models.CharField(max_length=100, verbose_name=_('Account Name'))
    role = models.CharField(max_length=25, choices=ACCOUNT_ROLES, verbose_name=_('Account Role'))
    balance_type = models.CharField(max_length=6, choices=BALANCE_TYPE, verbose_name=_('Account Balance Type'))
    locked = models.BooleanField(default=False, verbose_name=_('Locked'))
    active = models.BooleanField(default=False, verbose_name=_('Active'))
    coa = models.ForeignKey('django_ledger.ChartOfAccountModel',
                            on_delete=models.CASCADE,
                            editable=False,
                            verbose_name=_('Chart of Accounts'),
                            related_name='accounts')
    on_coa = AccountModelManager()

    class Meta:
        abstract = True
        ordering = ['-created']
        verbose_name = _('Account')
        verbose_name_plural = _('Accounts')
        unique_together = [
            ('coa', 'code')
        ]
        indexes = [
            models.Index(fields=['role']),
            models.Index(fields=['balance_type']),
            models.Index(fields=['active']),
            models.Index(fields=['coa']),
            models.Index(fields=['role', 'balance_type', 'active']),
        ]

    def __str__(self):
        return '{x1} - {x5}: {x2} ({x3}/{x4})'.format(x1=self.role_bs.upper(),
                                                      x2=self.name,
                                                      # pylint: disable=no-member
                                                      x3=self.role.upper(),
                                                      x4=self.balance_type,
                                                      x5=self.code)

    @property
    def role_bs(self):
        return BS_ROLES.get(self.role)

    def is_debit(self):
        return self.balance_type == DEBIT

    def is_credit(self):
        return self.balance_type == CREDIT

    def clean(self):
        # pylint: disable=unsupported-membership-test
        if ' ' in self.code:
            raise ValidationError(_('Account code must not contain spaces'))


class AccountModel(AccountModelAbstract):
    """
    Base Account Model from Account Model Abstract Class
    """

django-ledger/django_ledger/models/bank_account.py
"""
Django Ledger created by Miguel Sanda <msanda@arrobalytics.com>.
Copyright© EDMA Group Inc licensed under the GPLv3 Agreement.

Contributions to this module:
Miguel Sanda <msanda@arrobalytics.com>
"""

from uuid import uuid4

from django.core.exceptions import ValidationError
from django.core.validators import int_list_validator
from django.db import models
from django.db.models import Q
from django.utils.translation import gettext_lazy as _

from django_ledger.models import CreateUpdateMixIn
from django_ledger.models.utils import LazyLoader

lazy_loader = LazyLoader()


class BankAccountModelManager(models.Manager):

    def for_entity(self, entity_slug: str, user_model):
        qs = self.get_queryset()
        return qs.filter(
            Q(ledger__entity__slug__exact=entity_slug) &
            (
                    Q(ledger__entity__admin=user_model) |
                    Q(ledger__entity__managers__in=[user_model])
            )
        )


class BackAccountModelAbstract(CreateUpdateMixIn):
    REL_NAME_PREFIX = 'bank'
    ACCOUNT_TYPES = [
        ('checking', _('Checking')),
        ('savings', _('Savings')),
        ('money_mkt', _('Money Market')),
    ]

    uuid = models.UUIDField(default=uuid4, editable=False, primary_key=True)
    name = models.CharField(max_length=150, null=True, blank=True)
    account_number = models.CharField(max_length=30, null=True, blank=True,
                                      validators=[
                                          int_list_validator(sep='', message=_('Only digits allowed'))
                                      ])
    routing_number = models.CharField(max_length=30, null=True, blank=True,
                                      validators=[
                                          int_list_validator(sep='', message=_('Only digits allowed'))
                                      ])
    aba_number = models.CharField(max_length=30, null=True, blank=True)
    account_type = models.CharField(choices=ACCOUNT_TYPES, max_length=10)
    cash_account = models.ForeignKey('django_ledger.AccountModel',
                                     on_delete=models.CASCADE,
                                     verbose_name=_('Cash Account'),
                                     related_name=f'{REL_NAME_PREFIX}_cash_account',
                                     null=True, blank=True)
    ledger = models.OneToOneField('django_ledger.LedgerModel',
                                  editable=False,
                                  verbose_name=_('Ledger'),
                                  on_delete=models.CASCADE)
    active = models.BooleanField(default=True)
    hidden = models.BooleanField(default=False)
    objects = BankAccountModelManager()

    def configure(self,
                  entity_slug,
                  user_model,
                  posted_ledger: bool = True):
        EntityModel = lazy_loader.get_entity_model()
        if isinstance(entity_slug, str):
            entity_model = EntityModel.objects.for_user(
                user_model=user_model).get(
                slug__exact=entity_slug)
        elif isinstance(entity_slug, EntityModel):
            entity_model = entity_slug
        else:
            raise ValidationError('entity_slug must be an instance of str or EntityModel')

        LedgerModel = lazy_loader.get_ledger_model()
        acc_number = self.account_number
        ledger_model = LedgerModel.objects.create(
            entity=entity_model,
            posted=posted_ledger,
            # pylint: disable=unsubscriptable-object
            name=f'Bank Account {"***" + acc_number[-4:]}'
        )
        ledger_model.clean()
        self.ledger = ledger_model
        return self

    class Meta:
        abstract = True
        verbose_name = _('Bank Account')
        indexes = [
            models.Index(fields=['ledger']),
            models.Index(fields=['account_type']),
            models.Index(fields=['cash_account', 'account_type'])
        ]
        unique_together = [
            ('cash_account', 'account_number', 'routing_number')
        ]

    # pylint: disable=invalid-str-returned
    def __str__(self):
        # pylint: disable=bad-option-value
        return self.name


class BankAccountModel(BackAccountModelAbstract):
    """
    Base Bank Account Model
    """

django-ledger/django_ledger/models/coa.py
"""
Django Ledger created by Miguel Sanda <msanda@arrobalytics.com>.
Copyright© EDMA Group Inc licensed under the GPLv3 Agreement.

Contributions to this module:
Miguel Sanda <msanda@arrobalytics.com>
"""

from uuid import uuid4

from django.contrib.auth import get_user_model
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.db.models import Manager, Q
from django.utils.translation import gettext_lazy as _

from django_ledger.models.mixins import CreateUpdateMixIn, SlugNameMixIn

UserModel = get_user_model()


def get_coa_account(coa_model, code):
    try:
        qs = coa_model.acc_assignments.available()
        acc_model = qs.get(account__code__iexact=code)
        return acc_model
    except ObjectDoesNotExist:
        raise ValueError(
            'Account {acc} is either not assigned, inactive, locked or non existent for CoA: {coa}'.format(
                acc=code,
                coa=coa_model.__str__()
            ))


def make_account_active(coa_model, account_codes: str or list):
    if isinstance(account_codes, str):
        account_codes = [account_codes]
    qs = coa_model.accounts.all()
    acc = qs.filter(code__in=account_codes)
    acc.update(active=True)


class ChartOfAccountModelManager(Manager):

    def for_entity(self, entity_slug: str, user_model):
        qs = self.get_queryset()
        return qs.filter(
            Q(entity__slug__iexact=entity_slug) &
            (
                    Q(entity__admin=user_model) |
                    Q(entity__managers__in=[user_model])
            )
        )


class ChartOfAccountModelAbstract(SlugNameMixIn,
                                  CreateUpdateMixIn):
    """
    Base Chart of Accounts Model Abstract
    """

    uuid = models.UUIDField(default=uuid4, editable=False, primary_key=True)
    entity = models.OneToOneField('django_ledger.EntityModel',
                                  editable=False,
                                  related_name='coa',
                                  verbose_name=_('Entity'),
                                  on_delete=models.CASCADE)
    locked = models.BooleanField(default=False, verbose_name=_('Locked'))
    description = models.TextField(verbose_name=_('CoA Description'), null=True, blank=True)
    objects = ChartOfAccountModelManager()

    class Meta:
        abstract = True
        ordering = ['-created']
        verbose_name = _('Chart of Account')
        verbose_name_plural = _('Chart of Accounts')
        indexes = [
            models.Index(fields=['entity'])
        ]

    def __str__(self):
        return f'{self.slug}: {self.name}'


class ChartOfAccountModel(ChartOfAccountModelAbstract):
    """
    Base ChartOfAccounts Model
    """

django-ledger/django_ledger/models/customer.py
"""
Django Ledger created by Miguel Sanda <msanda@arrobalytics.com>.
Copyright© EDMA Group Inc licensed under the GPLv3 Agreement.

Contributions to this module:
Miguel Sanda <msanda@arrobalytics.com>
"""

from uuid import uuid4

from django.core.validators import MinValueValidator
from django.db import models
from django.utils.translation import gettext_lazy as _

from django_ledger.models.mixins import ContactInfoMixIn, CreateUpdateMixIn, SlugNameMixIn
from django.db.models import Q


class CustomerModelManager(models.Manager):

    def for_entity(self, entity_slug: str, user_model):
        qs = self.get_queryset()
        return qs.filter(
            Q(entity__slug__exact=entity_slug) &
            Q(active=True) &
            (
                    Q(entity__admin=user_model) |
                    Q(entity__managers__in=[user_model])
            )
        )


class CustomerModel(ContactInfoMixIn, CreateUpdateMixIn):
    uuid = models.UUIDField(default=uuid4, editable=False, primary_key=True)
    customer_name = models.CharField(max_length=100)
    entity = models.ForeignKey('django_ledger.EntityModel',
                               editable=False,
                               on_delete=models.CASCADE,
                               verbose_name=_('Customer Entity'),
                               related_name='customers')
    description = models.TextField()
    active = models.BooleanField(default=True)
    hidden = models.BooleanField(default=False)

    additional_info = models.JSONField(null=True, blank=True)

    objects = CustomerModelManager()

    class Meta:
        verbose_name = _('Customer')
        indexes = [
            models.Index(fields=['created']),
            models.Index(fields=['updated']),
            models.Index(fields=['active']),
            models.Index(fields=['hidden']),
        ]
        unique_together = [
            ('entity', 'customer_name')
        ]

    def __str__(self):
        return f'Customer: {self.customer_name}'

django-ledger/django_ledger/models/mpesa.py
from django.contrib.auth.models import User
from django.db import models
from datetime import datetime
from django.contrib.auth import get_user_model



from django.db.models.deletion import CASCADE
from django.db.models.fields import NullBooleanField

user= get_user_model()

class Mpesa_Transaction(models.Model):
    #user=models.ForeignKey(user, on_delete=CASCADE,blank=True,null=True)
    phone=models.IntegerField()
    amount=models.IntegerField()
    transaction_mpesa_id=models.CharField(max_length=15, null=False)

    def __str__(self):
        return self.transaction_mpesa_id
    @property
    def get_total_mpesa_trans(self):
        total_mpesa_transaction=self.mpesa_transaction_set.all()
        sum=0
        total=sum+(single_transaction for single_transaction in total_mpesa_transaction)
        return total




    

django-ledger/django_ledger/templates/django_ledger/tags/account_txs_table.html
{% load django_ledger %}
{% load trans from i18n %}

<div class="table-container">
    <table class="table is-fullwidth is-narrow is-striped is-bordered django-ledger-table-bottom-margin-75">
        <tr>
            <th class="has-text-centered">Date</th>
            <th class="has-text-centered">Credit</th>
            <th class="has-text-centered">Debit</th>
            <th class="has-text-centered">Description</th>
            <th class="has-text-centered">Actions</th>
        </tr>
        {% for tx in transactions %}
            <tr class="has-text-centered">
                <td>{{ tx.journal_entry.date }}</td>
                <td>{% if tx.tx_type == 'credit' %}${{ tx.amount | currency_format }}{% endif %}</td>
                <td>{% if tx.tx_type == 'debit' %}${{ tx.amount | currency_format }}{% endif %}</td>
                <td>{{ tx.description }}</td>
                <td>
                    <div class="dropdown is-right is-hoverable" id="tx-action-{{ tx.uuid }}">
                        <div class="dropdown-trigger">
                            <button class="button is-small is-rounded is-outlined"
                                    aria-haspopup="true"
                                    aria-controls="dropdown-menu">
                                <span>{% trans 'Actions' %}</span>
                                <span class="icon is-small">{% icon 'bi:arrow-down' 24 %}</span>
                            </button>
                        </div>
                        <div class="dropdown-menu" id="dropdown-menu-{{ tx.uuid }}" role="menu">
                            <div class="dropdown-content">
                                <a href="{% url 'django_ledger:je-detail' entity_slug=entity_slug ledger_pk=tx.journal_entry.ledger.uuid je_pk=tx.journal_entry.uuid %}"
                                   class="dropdown-item has-text-success">View JE</a>
                                {% if tx.journal_entry.ledger.billmodel %}
                                    <a href="{% url 'django_ledger:bill-detail' entity_slug=entity_slug bill_pk=tx.journal_entry.ledger.billmodel.uuid %}"
                                       class="dropdown-item has-text-primary">View Bill</a>
                                {% elif tx.journal_entry.ledger.invoicemodel %}
                                    <a href="{% url 'django_ledger:invoice-detail' entity_slug=entity_slug invoice_pk=tx.journal_entry.ledger.invoicemodel.uuid %}"
                                       class="dropdown-item has-text-info">View Invoice</a>
                                {% endif %}

                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        {% endfor %}
        <tr class="has-text-weight-bold">
            <td class="has-text-right">Total</td>
            <td class="has-text-centered">${{ total_credits | currency_format }}</td>
            <td class="has-text-centered">${{ total_debits | currency_format }}</td>
            <td></td>
            <td></td>
        </tr>
    </table>
</div>

django-ledger/django_ledger/templates/django_ledger/tags/accounts_table.html
{% load i18n %}
{% load django_ledger %}

<div class="table-container">
    <table class="table is-fullwidth is-striped is-narrow django-ledger-table-bottom-margin-75">
        <thead>
            {% if title %}
                <tr>
                    <td><h2 class="is-size-3 has-text-weight-light">{{ title }}</h2></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            {% endif %}
            <tr>
                <th>{% trans 'Role' %}</th>
                <th>{% trans 'Parent' %}</th>
                <th>{% trans 'Code' %}</th>
                <th>{% trans 'Account Name' %}</th>
                <th>{% trans 'Balance Type' %}</th>
                <th>{% trans 'Active' %}</th>
                <th>{% trans 'Locked' %}</th>
                <th>{% trans 'Actions' %}</th>
            </tr>
        </thead>

        <tbody>
            {% for account in accounts %}
                <tr>
                    <td>{{ account.get_role_display }}</td>
                    <td>{{ account.parent.code }}</td>
                    <td>{{ account.code }}</td>
                    <td>{{ account.name }}</td>
                    <td class="has-text-centered">
                        {% if account.is_debit %}
                            <span class="icon has-text-info-dark">{% icon 'bi:arrow-bar-down' 24 %}</span>
                        {% elif account.is_credit %}
                            <span class="icon has-text-warning-dark">{% icon 'bi:arrow-bar-up' 24 %}</span>
                        {% endif %}
                    </td>
                    <td class="has-text-centered">
                        {% if account.active %}
                            <span class="icon has-text-success-dark">
                                {% icon 'ant-design:check-circle-filled' 24 %}
                            </span>
                        {% endif %}
                    </td>
                    <td class="has-text-centered">
                        {% if account.locked %}
                            <span class="icon has-text-success-dark">
                                {% icon 'bi:lock-fill' 24 %}
                            </span>
                        {% elif not account.locked %}
                            <span class="icon has-text-danger-dark">
                                {% icon 'bx:bx-lock-open-alt' 24 %}
                            </span>
                        {% endif %}
                    </td>
                    <td>
                        <div class="dropdown is-right is-hoverable" id="account-action-{{ account.uuid }}">
                            <div class="dropdown-trigger">
                                <button class="button is-small is-rounded is-outlined"
                                        aria-haspopup="true"
                                        aria-controls="dropdown-menu">
                                    <span>Actions</span>
                                    <span class="icon is-small">{% icon 'bi:arrow-down' 24 %}</span>
                                </button>
                            </div>
                            <div class="dropdown-menu" id="dropdown-menu-{{ account.uuid }}" role="menu">
                                <div class="dropdown-content">
                                    <a href="{% url 'django_ledger:account-detail' entity_slug=entity_slug account_pk=account.uuid %}"
                                       class="dropdown-item has-text-success">{% trans 'Detail' %}</a>
                                    <a href="{% url 'django_ledger:account-update' entity_slug=entity_slug account_pk=account.uuid %}"
                                       class="dropdown-item has-text-warning">{% trans 'Update' %}</a>
                                    <a href="{% url 'django_ledger:account-create-child' entity_slug=entity_slug parent_account_pk=account.uuid %}"
                                       class="dropdown-item has-text-info">{% trans 'Create Child Account' %}</a>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
            {% endfor %}
    </table>
</div>

django-ledger/django_ledger/templates/django_ledger/tags/activity_form.html
{% load i18n %}

<form action="{{ form_path }}" method="get">

    <div class="field is-horizontal">

        <div class="field-label is-small">
            <label for="{{ activity_form.activity.id_for_label }}"
                   class="label">{{ activity_form.activity.label }}
            </label>
        </div>

        <div class="field-body">
            <div class="field has-addons">
                <div class="control is-expanded">
                    <div class="select is-small is-fullwidth">{{ activity_form.activity }}</div>
                </div>
                <div class="control">
                    <button type="submit" class="button is-primary is-small">Choose</button>
                </div>
            </div>
        </div>

    </div>

</form>

django-ledger/django_ledger/templates/django_ledger/tags/bank_accounts_table.html
{% load django_ledger %}
{% load i18n %}

<div class="table-container">
    <table class="table is-fullwidth is-narrow is-striped is-bordered django-ledger-table-bottom-margin-75">
        <thead>
        <tr>
            <th class="has-text-centered">Name</th>
            <th class="has-text-centered">Account Number</th>
            <th class="has-text-centered">Routing Number</th>
            <th class="has-text-centered">Type</th>
            <th class="has-text-centered">Cash Account</th>
            <th class="has-text-centered">Active</th>
            <th class="has-text-centered">Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for bank_acc in bank_account_qs %}
            <tr class="has-text-centered">
                <td>{{ bank_acc.name }}</td>
                <td>{{ bank_acc.account_number | last_four }}</td>
                <td>{{ bank_acc.routing_number | last_four }}</td>
                <td>{{ bank_acc.get_account_type_display }}</td>
                <td>{{ bank_acc.cash_account }}</td>
                <td>
                    {% if bank_acc.active %}
                        <span class="icon has-text-success">{% icon 'ant-design:check-circle-filled' 24 %}</span>
                    {% else %}
                        <span class="icon is-small has-text-danger">{% icon 'maki:roadblock-11' 24 %}</span>
                    {% endif %}
                </td>
                <td>
                    <div class="dropdown is-right is-hoverable"
                         id="bank-action-{{ bank_acc.uuid }}">
                        <div class="dropdown-trigger">
                            <button class="button is-small is-rounded is-outlined is-dark"
                                    aria-haspopup="true"
                                    aria-controls="dropdown-menu">
                                <span>{% trans 'Actions' %}</span>
                                <span class="icon is-small">{% icon 'bi:arrow-down' 24 %}</span>
                            </button>
                        </div>

                        <div class="dropdown-menu"
                             id="dropdown-menu-{{ bank_acc.uuid }}"
                             role="menu">
                            <div class="dropdown-content">
                                <a href="{% url 'django_ledger:bank-account-update' entity_slug=entity_slug bank_account_pk=bank_acc.uuid %}"
                                   class="dropdown-item has-text-weight-bold has-text-info">{% trans 'Update' %}</a>
                            </div>
                        </div>
                    </div>


                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

</div>

django-ledger/django_ledger/templates/django_ledger/tags/data_import_job_list_table.html
{% load django_ledger %}
{% load i18n %}

<div class="table-container">
    <table class="table is-fullwidth is-narrow is-striped mb-3 django-ledger-table-bottom-margin-75">
        <thead>
        <tr>
            <th>Status</th>
            <th>Description</th>
            <th>Ledger</th>
            <th>Created</th>
            <th>Completed</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>

        {% for job in import_jobs %}
            <tr>
                <td>{{ job.status }}</td>
                <td>{{ job.description }}</td>
                <td>{{ job.ledger }}</td>
                <td>{{ job.created }}</td>
                <td>{% if job.completed %}
                    <span class="icon is-small has-text-success"><i class="icon mdi mdi-check-bold"></i></span>
                {% else %}
                    <span class="icon is-small has-text-danger"><i class="icon mdi mdi-minus-circle"></i></span>
                {% endif %}</td>
                <td>
                    <div class="dropdown is-right" id="customer-action-{{ job.uuid }}">

                        <div class="dropdown-trigger">
                            <button class="button is-small is-rounded is-outlined is-dark"
                                    aria-haspopup="true"
                                    onclick="djLedger.toggleDropdown('customer-action-{{ job.uuid }}')"
                                    aria-controls="dropdown-menu">
                                <span>Actions</span>
                                <span class="icon is-small">{% icon 'bi:arrow-down' 24 %}</span>
                            </button>
                        </div>

                        <div class="dropdown-menu"
                             id="dropdown-menu-{{ customer.uuid }}"
                             role="menu">
                            <div class="dropdown-content">
                                <a href="{% url 'django_ledger:data-import-job-txs' entity_slug=view.kwargs.entity_slug job_pk=job.uuid %}"
                                   class="dropdown-item has-text-weight-bold has-text-info">{% trans 'Manage' %}</a>
                            </div>
                        </div>
                    </div>

                </td>
            </tr>
        {% endfor %}

        </tbody>
    </table>

</div>

django-ledger/django_ledger/templates/django_ledger/tags/data_import_job_txs_imported.html
<div class="table-container">
    <table class="table is-narrow is-fullwidth is-bordered django-ledger-table-bottom-margin-75">
        <thead>
        <tr class="has-text-centered is-error">
            <th>Dated Posted</th>
            <th>Description</th>
            <th>Amount</th>
            <th>Map To</th>
            <th>TX</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for imported_tx in imported_txs %}
            <tr>
                <td>{{ imported_tx.date_posted }}</td>
                <td>{{ imported_tx.name }}</td>
                <td class="{% if imported_tx.amount < 0 %}has-text-danger{% endif %} has-text-centered">
                    ${{ imported_tx.amount }}</td>
                <td>{{ imported_tx.earnings_account }}</td>
                <td>{{ imported_tx.tx }}</td>
                <td class="has-text-centered">
                    <a href="" class="button is-small is-primary">View</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>