django-ledger/dev_env/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django_ledger.urls', namespace='django_ledger')),
]

try:
    # checking for graphene_django installation to provide and enable graphql services...
    from graphene_django.views import GraphQLView
    from django_ledger.contrib.django_ledger_graphql.api import schema

    urlpatterns += [
        path('graphql/', csrf_exempt(GraphQLView.as_view(graphiql=True, schema=schema)))
    ]
except ImportError:
    pass

django-ledger/django_ledger/models/accounts.py
"""
Django Ledger created by Miguel Sanda <msanda@arrobalytics.com>.
Copyright© EDMA Group Inc licensed under the GPLv3 Agreement.

Contributions to this module:
Miguel Sanda <msanda@arrobalytics.com>
"""
from typing import Union
from uuid import uuid4

from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Q
from django.utils.translation import gettext_lazy as _

from django_ledger.io.roles import ACCOUNT_ROLES, BS_ROLES, GROUP_INVOICE, GROUP_BILL
from django_ledger.models.mixins import CreateUpdateMixIn, ParentChildMixIn

DEBIT = 'debit'
CREDIT = 'credit'


class AccountModelQuerySet(models.QuerySet):

    def active(self):
        return self.filter(active=True)

    def with_roles(self, roles: Union[list, str]):
        if isinstance(roles, str):
            roles = [roles]
        return self.filter(role__in=roles)


class AccountModelManager(models.Manager):

    def get_queryset(self):
        return AccountModelQuerySet(self.model, using=self._db)

    def for_entity(self, user_model, entity_slug: str, coa_slug: str = None):
        qs = self.get_queryset()
        qs = qs.filter(
            Q(coa__entity__slug__exact=entity_slug) &
            (
                    Q(coa__entity__admin=user_model) |
                    Q(coa__entity__managers__in=[user_model])
            )
        ).order_by('code')
        if coa_slug:
            qs = qs.filter(coa__slug__iexact=coa_slug)
        return qs

    def with_roles(self, roles: Union[list, str], entity_slug: str, user_model):
        if isinstance(roles, str):
            roles = [roles]
        qs = self.for_entity(entity_slug=entity_slug, user_model=user_model)
        return qs.filter(role__in=roles)

    def with_roles_available(self, roles: Union[list, str], entity_slug: str, user_model):
        if isinstance(roles, str):
            roles = [roles]
        qs = self.for_entity_available(entity_slug=entity_slug, user_model=user_model)
        return qs.filter(role__in=roles)

    def for_entity_available(self, user_model, entity_slug: str, coa_slug: str = None):
        qs = self.for_entity(
            user_model=user_model,
            entity_slug=entity_slug,
            coa_slug=coa_slug)
        return qs.filter(
            active=True,
            locked=False
        )

    def for_invoice(self, user_model, entity_slug: str, coa_slug: str = None):
        qs = self.for_entity_available(
            user_model=user_model,
            entity_slug=entity_slug,
            coa_slug=coa_slug)
        return qs.filter(role__in=GROUP_INVOICE)

    def for_bill(self, user_model, entity_slug: str, coa_slug: str = None):
        qs = self.for_entity_available(
            user_model=user_model,
            entity_slug=entity_slug,
            coa_slug=coa_slug)
        return qs.filter(role__in=GROUP_BILL)


class AccountModelAbstract(ParentChildMixIn, CreateUpdateMixIn):
    """
    Djetler's Base Account Model Abstract
    """
    BALANCE_TYPE = [
        (CREDIT, _('Credit')),
        (DEBIT, _('Debit'))
    ]

    uuid = models.UUIDField(default=uuid4, editable=False, primary_key=True)
    code = models.CharField(max_length=10, verbose_name=_('Account Code'))
    name = models.CharField(max_length=100, verbose_name=_('Account Name'))
    role = models.CharField(max_length=25, choices=ACCOUNT_ROLES, verbose_name=_('Account Role'))
    balance_type = models.CharField(max_length=6, choices=BALANCE_TYPE, verbose_name=_('Account Balance Type'))
    locked = models.BooleanField(default=False, verbose_name=_('Locked'))
    active = models.BooleanField(default=False, verbose_name=_('Active'))
    coa = models.ForeignKey('django_ledger.ChartOfAccountModel',
                            on_delete=models.CASCADE,
                            editable=False,
                            verbose_name=_('Chart of Accounts'),
                            related_name='accounts')
    on_coa = AccountModelManager()

    class Meta:
        abstract = True
        ordering = ['-created']
        verbose_name = _('Account')
        verbose_name_plural = _('Accounts')
        unique_together = [
            ('coa', 'code')
        ]
        indexes = [
            models.Index(fields=['role']),
            models.Index(fields=['balance_type']),
            models.Index(fields=['active']),
            models.Index(fields=['coa']),
            models.Index(fields=['role', 'balance_type', 'active']),
        ]

    def __str__(self):
        return '{x1} - {x5}: {x2} ({x3}/{x4})'.format(x1=self.role_bs.upper(),
                                                      x2=self.name,
                                                      # pylint: disable=no-member
                                                      x3=self.role.upper(),
                                                      x4=self.balance_type,
                                                      x5=self.code)

    @property
    def role_bs(self):
        return BS_ROLES.get(self.role)

    def is_debit(self):
        return self.balance_type == DEBIT

    def is_credit(self):
        return self.balance_type == CREDIT

    def clean(self):
        # pylint: disable=unsupported-membership-test
        if ' ' in self.code:
            raise ValidationError(_('Account code must not contain spaces'))


class AccountModel(AccountModelAbstract):
    """
    Base Account Model from Account Model Abstract Class
    """

django-ledger/django_ledger/models/invoice.py
"""
Django Ledger created by Miguel Sanda <msanda@arrobalytics.com>.
Copyright© EDMA Group Inc licensed under the GPLv3 Agreement.

Contributions to this module:
Miguel Sanda <msanda@arrobalytics.com>
"""
from datetime import date
from decimal import Decimal
from random import choices
from string import ascii_uppercase, digits
from uuid import uuid4

from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Q, Sum, Count
from django.db.models.signals import post_delete
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.utils.timezone import localdate
from django.utils.translation import gettext_lazy as _

from django_ledger.models import LazyLoader
from django_ledger.models.entity import EntityModel
from django_ledger.models.mixins import CreateUpdateMixIn, LedgerWrapperMixIn, MarkdownNotesMixIn

UserModel = get_user_model()

lazy_loader = LazyLoader()

INVOICE_NUMBER_CHARS = ascii_uppercase + digits


def generate_invoice_number(length: int = 10, prefix: bool = True) -> str:
    """
    A function that generates a random bill identifier for new bill models.
    :param prefix:
    :param length: The length of the bill number.
    :return: A string representing a random bill identifier.
    """
    invoice_number = ''.join(choices(INVOICE_NUMBER_CHARS, k=length))
    if prefix:
        invoice_number = 'I-' + invoice_number
    return invoice_number


class InvoiceModelQuerySet(models.QuerySet):

    def paid(self):
        return self.filter(invoice_status__exact=InvoiceModel.INVOICE_STATUS_PAID)

    def approved(self):
        return self.filter(invoice_status__exact=InvoiceModel.INVOICE_STATUS_APPROVED)


class InvoiceModelManager(models.Manager):

    def get_queryset(self):
        return InvoiceModelQuerySet(self.model, using=self._db)

    def for_entity(self, entity_slug, user_model):
        qs = self.get_queryset().filter(
            Q(ledger__entity__admin=user_model) |
            Q(ledger__entity__managers__in=[user_model])
        )
        if isinstance(entity_slug, EntityModel):
            return qs.filter(ledger__entity=entity_slug)
        elif isinstance(entity_slug, str):
            return qs.filter(ledger__entity__slug__exact=entity_slug)

    def for_entity_unpaid(self, entity_slug, user_model):
        qs = self.for_entity(entity_slug=entity_slug, user_model=user_model)
        return qs.approved()


class InvoiceModelAbstract(LedgerWrapperMixIn,
                           MarkdownNotesMixIn,
                           CreateUpdateMixIn):
    IS_DEBIT_BALANCE = True
    REL_NAME_PREFIX = 'invoice'

    INVOICE_STATUS_DRAFT = 'draft'
    INVOICE_STATUS_REVIEW = 'in_review'
    INVOICE_STATUS_APPROVED = 'approved'
    INVOICE_STATUS_PAID = 'paid'
    INVOICE_STATUS_VOID = 'void'
    INVOICE_STATUS_CANCELED = 'canceled'

    INVOICE_STATUS = [
        (INVOICE_STATUS_DRAFT, _('Draft')),
        (INVOICE_STATUS_REVIEW, _('In Review')),
        (INVOICE_STATUS_APPROVED, _('Approved')),
        (INVOICE_STATUS_PAID, _('Paid')),
        (INVOICE_STATUS_VOID, _('Void')),
        (INVOICE_STATUS_CANCELED, _('Canceled'))
    ]

    uuid = models.UUIDField(default=uuid4, editable=False, primary_key=True)
    invoice_number = models.SlugField(max_length=20, unique=True, verbose_name=_('Invoice Number'))
    invoice_status = models.CharField(max_length=10, choices=INVOICE_STATUS, default=INVOICE_STATUS[0][0],
                                      verbose_name=_('Invoice Status'))
    customer = models.ForeignKey('django_ledger.CustomerModel',
                                 on_delete=models.RESTRICT,
                                 verbose_name=_('Customer'))

    cash_account = models.ForeignKey('django_ledger.AccountModel',
                                     on_delete=models.RESTRICT,
                                     verbose_name=_('Cash Account'),
                                     related_name=f'{REL_NAME_PREFIX}_cash_account')
    prepaid_account = models.ForeignKey('django_ledger.AccountModel',
                                        on_delete=models.RESTRICT,
                                        verbose_name=_('Prepaid Account'),
                                        related_name=f'{REL_NAME_PREFIX}_prepaid_account')
    unearned_account = models.ForeignKey('django_ledger.AccountModel',
                                         on_delete=models.RESTRICT,
                                         verbose_name=_('Unearned Account'),
                                         related_name=f'{REL_NAME_PREFIX}_unearned_account')

    additional_info = models.JSONField(blank=True,
                                       null=True,
                                       verbose_name=_('Invoice Additional Info'))
    invoice_items = models.ManyToManyField('django_ledger.ItemModel',
                                           through='django_ledger.ItemThroughModel',
                                           through_fields=('invoice_model', 'item_model'),
                                           verbose_name=_('Invoice Items'))

    ce_model = models.ForeignKey('django_ledger.EstimateModel',
                                 on_delete=models.RESTRICT,
                                 null=True,
                                 blank=True,
                                 verbose_name=_('Associated Customer Job/Estimate'))

    draft_date = models.DateField(null=True, blank=True, verbose_name=_('Draft Date'))
    in_review_date = models.DateField(null=True, blank=True, verbose_name=_('In Review Date'))
    approved_date = models.DateField(null=True, blank=True, verbose_name=_('Approved Date'))
    paid_date = models.DateField(null=True, blank=True, verbose_name=_('Paid Date'))
    void_date = models.DateField(null=True, blank=True, verbose_name=_('Void Date'))
    canceled_date = models.DateField(null=True, blank=True, verbose_name=_('Canceled Date'))

    objects = InvoiceModelManager()

    class Meta:
        abstract = True
        ordering = ['-updated']
        verbose_name = _('Invoice')
        verbose_name_plural = _('Invoices')
        indexes = [
            models.Index(fields=['due_date']),
            models.Index(fields=['invoice_status']),
            models.Index(fields=['terms']),
            models.Index(fields=['customer']),

            models.Index(fields=['cash_account']),
            models.Index(fields=['prepaid_account']),
            models.Index(fields=['unearned_account']),

            models.Index(fields=['draft_date']),
            models.Index(fields=['in_review_date']),
            models.Index(fields=['approved_date']),
            models.Index(fields=['paid_date']),
            models.Index(fields=['void_date']),
            models.Index(fields=['canceled_date']),
        ]

    def __str__(self):
        return f'Invoice: {self.invoice_number}'

    def configure(self,
                  entity_slug: str or EntityModel,
                  user_model: UserModel,
                  post_ledger: bool = False):

        if isinstance(entity_slug, str):
            entity_qs = EntityModel.objects.for_user(
                user_model=user_model)
            entity_model: EntityModel = get_object_or_404(entity_qs, slug__exact=entity_slug)
        elif isinstance(entity_slug, EntityModel):
            entity_model = entity_slug
        else:
            raise ValidationError('entity_slug must be an instance of str or EntityModel')

        if not self.invoice_number:
            self.invoice_number = generate_invoice_number()

        LedgerModel = lazy_loader.get_ledger_model()

        ledger_model = LedgerModel.objects.create(
            entity=entity_model,
            posted=post_ledger,
            name=f'Invoice {self.invoice_number}',
        )
        ledger_model.clean()
        self.clean()
        self.ledger = ledger_model
        return ledger_model, self

    # STATE...
    def is_draft(self) -> bool:
        return self.invoice_status == self.INVOICE_STATUS_DRAFT

    def is_review(self) -> bool:
        return self.invoice_status == self.INVOICE_STATUS_REVIEW

    def is_approved(self) -> bool:
        return self.invoice_status == self.INVOICE_STATUS_APPROVED

    def is_paid(self) -> bool:
        return self.invoice_status == self.INVOICE_STATUS_PAID

    def is_canceled(self) -> bool:
        return self.invoice_status == self.INVOICE_STATUS_CANCELED

    def is_void(self) -> bool:
        return self.invoice_status == self.INVOICE_STATUS_VOID

    # PERMISSIONS....
    def can_draft(self):
        return self.is_review()

    def can_review(self):
        return all([
            self.is_configured(),
            self.is_draft()
        ])

    def can_approve(self):
        return self.is_review()

    def can_pay(self):
        return self.is_approved()

    def can_cancel(self):
        return any([
            self.is_draft(),
            self.is_review()
        ])

    def can_void(self):
        return self.is_approved()

    def can_delete(self):
        return any([
            self.is_review(),
            self.is_draft()
        ])

    def can_edit_items(self):
        return self.is_draft()

    def can_migrate(self):
        if not self.is_approved():
            return False
        return super(InvoiceModelAbstract, self).can_migrate()

    def can_bind_estimate(self, estimate_model, raise_exception: bool = False) -> bool:
        if self.ce_model_id:
            if raise_exception:
                raise ValidationError(f'Invoice {self.invoice_number} already bound to '
                                      f'Estimate {self.ce_model.estimate_number}')
            return False
        is_approved = estimate_model.is_approved()
        if not is_approved and raise_exception:
            raise ValidationError(f'Cannot bind estimate that is not approved.')
        return all([

django-ledger/django_ledger/models/mpesa.py
from django.contrib.auth.models import User
from django.db import models
from datetime import datetime
from django.contrib.auth import get_user_model



from django.db.models.deletion import CASCADE
from django.db.models.fields import NullBooleanField

user= get_user_model()

class Mpesa_Transaction(models.Model):
    #user=models.ForeignKey(user, on_delete=CASCADE,blank=True,null=True)
    phone=models.IntegerField()
    amount=models.IntegerField()
    transaction_mpesa_id=models.CharField(max_length=15, null=False)

    def __str__(self):
        return self.transaction_mpesa_id
    @property
    def get_total_mpesa_trans(self):
        total_mpesa_transaction=self.mpesa_transaction_set.all()
        sum=0
        total=sum+(single_transaction for single_transaction in total_mpesa_transaction)
        return total




    

django-ledger/django_ledger/templates/django_ledger/includes/breadcrumbs.html
{% load django_ledger %}
<div class="container djetler_mt_1">
    <div class="columns">
        <div class="column">
            {% nav_breadcrumbs %}
        </div>
    </div>
</div>

django-ledger/django_ledger/templates/django_ledger/includes/card_customer.html
{% load i18n %}
{% load django_ledger %}

<div class="card">
    <div class="card-header">
        <h2 class="card-header-title has-text-weight-light is-size-3">
            <span class="icon is-large">
                    {% icon 'bi:person-lines-fill' 36 %}</span>
            {% trans 'Customer Information' %}</h2>
    </div>
    <div class="card-content">
        <div class="content">
            <h1 class="has-text-weight-bold">
                {{ customer.customer_name }}
            </h1>
            <p>
                {% if customer.address_1 %}{{ customer.address_1 }}<br>{% endif %}
                {% if customer.address_2 %}{{ customer.address_2 }}<br>{% endif %}
                {% if customer.get_cszc %}{{ customer.get_cszc }}<br>{% endif %}
                {% if customer.phone %}{{ customer.phone }}<br>{% endif %}
                {% if customer.email %}{{ customer.email }}<br>{% endif %}
                {% if customer.website %}{{ customer.website }}<br>{% endif %}
            </p>
        </div>
    </div>
    <footer class="card-footer">
        <a href="{% url 'django_ledger:customer-update' customer_pk=customer.uuid entity_slug=view.kwargs.entity_slug %}"
           class="card-footer-item has-text-primary has-text-centered">{% trans 'Edit' %}</a>
    </footer>

</div>

django-ledger/django_ledger/templates/django_ledger/includes/card_entity.html
{% load django_ledger %}
{% now "Y" as current_year %}


<div class="card">
    <div class="card-content">
        <p class="title has-text-weight-light">
            <span class="icon is-medium">{% icon "ic:baseline-business" 36 %}</span>{{ entity.name }}
        </p>
        <p class="subtitle">{{ entity.address_1 }}</p>
        <p>Created: {{ entity.created | timesince }} ago</p>
    </div>
    <footer class="card-footer">
        <a href="{{ entity.get_dashboard_url }}" class="card-footer-item">Dashboard</a>
        <a href="{{ entity.get_manage_url }}" class="card-footer-item has-text-info">Manage</a>
        <a href="{{ entity.get_delete_url }}" class="card-footer-item has-text-danger">Delete</a>
    </footer>
</div>

django-ledger/django_ledger/templates/django_ledger/includes/card_invoice.html
{% load django_ledger %}
{% load i18n %}

{% if not create_invoice %}
    {% if style == 'dashboard' %}
        <div class="card">
            <div class="card-content">
                <p class="subtitle has-text-grey has-text-right">
                    <span class="icon">{% icon "bi:cash-stack" 16 %}</span>
                    {% trans 'Invoice' %}</p>
                <p class="title">{{ invoice.customer.customer_name }}</p>
                <p class="subtitle has-text-weight-light">{{ invoice.customer.address_1 }}</p>
                {% if not invoice.is_past_due %}
                    <p class="is-size-5 has-text-info">Due in: {{ invoice.due_date | timeuntil }}</p>
                {% else %}
                    <p class="has-text-danger has-text-weight-bold is-size-5">Past
                        Due: {{ invoice.due_date | timesince }} ago</p>
                {% endif %}
                {% if invoice.accrue %}
                    <p>Accrue: <span
                            class="icon has-text-success">{% icon 'ant-design:check-circle-filled' 24 %}</span>
                        {% else %}
                    <p>Accrue:
                    <span class="icon is-small has-text-danger">{% icon 'maki:roadblock-11' 24 %}</span>
                {% endif %}
                <p class="is-size-5 has-text-success">Owed to You:
                    {% currency_symbol %}{{ invoice.get_amount_open | currency_format }}</p>
                <p>Amount Paid: {% currency_symbol %}{{ invoice.amount_paid | currency_format }}</p>
                <p>Progressed: {{ invoice.get_progress | percentage }}</p><br>
                <progress class="progress is-medium is-success"
                          value="{{ invoice.get_progress_percent }}"
                          max="100">{{ invoice.get_progress | percentage }}
                </progress>
                {# MARK AS PAID MODAL #}
                {#                {% modal_action invoice 'get' entity_slug %}#}
            </div>
            <footer class="card-footer">
                <a href="{% url 'django_ledger:invoice-detail' entity_slug=entity_slug invoice_pk=invoice.uuid %}"
                   class="card-footer-item has-text-primary has-text-centered">{% trans 'View' %}</a>
                <a href="{% url 'django_ledger:invoice-update' entity_slug=entity_slug invoice_pk=invoice.uuid %}"
                   class="card-footer-item has-text-warning-dark has-text-centered">{% trans 'Update' %}</a>
                {% if not invoice.paid %}
                    <a onclick="djLedger.toggleModal('{{ invoice.get_html_id }}')"
                       class="card-footer-item has-text-info has-text-centered">{% trans 'Mark as Paid' %}</a>
                {% endif %}
            </footer>
        </div>
    {% elif style == 'invoice-detail' %}
        <div class="card">
            <div class="card-header">
                <h2 class="card-header-title has-text-weight-light is-size-3">
            <span class="icon is-large">
                    {% icon 'uil:bill' 36 %}</span>
                    {% trans 'Invoice Info' %}</h2>
            </div>
            <div class="card-content">

                {% if invoice.paid %}
                    <p class="is-size-3 has-text-dark">Is Paid
                        <span class="icon is-large has-text-success-dark">
                            {% icon 'ant-design:check-circle-filled' 48 %}
                        </span>
                    </p>
                    <p class="is-size-4">Amount Paid:
                        <span class="has-text-weight-bold">{% currency_symbol %}{{ invoice.amount_paid | currency_format }}</span>
                    </p>
                {% else %}
                    <p class="is-size-3 has-text-dark">Invoice Amount:
                        <span class="has-text-weight-bold">{% currency_symbol %}{{ invoice.amount_due | currency_format }}</span>
                    </p>
                    <p class="is-size-4">Invoice Status: {{ invoice.get_invoice_status_display }}</p>
                    {% if not invoice.is_past_due %}
                        <p class="is-size-4 has-text-info">Due in: {{ invoice.due_date | timeuntil }}</p>
                    {% else %}
                        <p class="has-text-danger has-text-weight-bold is-size-3">Past
                            Due: {{ invoice.due_date | timesince }} ago</p>
                    {% endif %}
                    <p class="is-size-5 has-text-success">Owed to You:
                        {% currency_symbol %}{{ invoice.get_amount_open | currency_format }}</p>

                    {% if invoice.accrue %}
                        <p>Accrue: <span
                                class="icon has-text-success">{% icon 'ant-design:check-circle-filled' 24 %}</span>
                        </p>
                    {% else %}
                        <p>Accrue:
                            <span class="icon is-small has-text-danger">{% icon 'maki:roadblock-11' 24 %}</span>
                        </p>
                    {% endif %}
                    <p>Amount Paid: {% currency_symbol %}{{ invoice.amount_paid | currency_format }}</p>
                    <p>Progressed: {{ invoice.get_progress_percent }}%</p><br>
                    <progress class="progress is-medium is-success"
                              value="{{ invoice.get_progress_percent }}"
                              max="100">
                        {{ invoice.get_progress | percentage }}
                    </progress>

                {% endif %}

                {# MARK AS PAID MODAL #}
                {#                {% modal_action invoice 'get' entity_slug %}#}

            </div>
            <footer class="card-footer">
                <a href="{% url 'django_ledger:invoice-update' entity_slug=entity_slug invoice_pk=invoice.uuid %}"
                   class="card-footer-item has-text-primary has-text-centered">{% trans 'Update' %}</a>

                {# MARK DRAFT #}
                {% if invoice.can_draft %}
                    <a onclick="djLedger.toggleModal('{{ invoice.get_mark_as_draft_html_id }}')"
                       id="{{ invoice.get_mark_as_review_html_id }}-button"
                       class="card-footer-item has-text-info has-text-centered">{% trans 'Mark as Draft' %}</a>
                    {# MARK AS DRAFT MODAL #}
                    {% modal_action_v2 invoice invoice.get_mark_as_draft_url invoice.get_mark_as_draft_message invoice.get_mark_as_draft_html_id %}
                {% endif %}

                {# MARK REVIEW #}
                {% if invoice.can_review %}
                    <a onclick="djLedger.toggleModal('{{ invoice.get_mark_as_review_html_id }}')"
                       id="{{ invoice.get_mark_as_review_html_id }}-button"
                       class="card-footer-item has-text-info has-text-centered">{% trans 'Mark as Review' %}</a>
                    {# MARK AS REVIEW MODAL #}
                    {% modal_action_v2 invoice invoice.get_mark_as_review_url invoice.get_mark_as_review_message invoice.get_mark_as_review_html_id %}
                {% endif %}

                {# MARK APPROVED #}
                {% if invoice.can_approve %}
                    <a onclick="djLedger.toggleModal('{{ invoice.get_mark_as_approved_html_id }}')"
                       id="{{ invoice.get_mark_as_approved_html_id }}-button"
                       class="card-footer-item has-text-info has-text-centered has-text-success">{% trans 'Approve' %}</a>
                    {# MARK AS APPROVED MODAL #}
                    {% modal_action_v2 invoice invoice.get_mark_as_approved_url invoice.get_mark_as_approved_message invoice.get_mark_as_approved_html_id %}
                {% endif %}

                {# MARK PAID #}
                {% if invoice.can_pay %}
                    <a onclick="djLedger.toggleModal('{{ invoice.get_mark_as_paid_html_id }}')"
                       id="{{ invoice.get_mark_as_paid_html_id }}-button"
                       class="card-footer-item has-text-info has-text-centered has-text-success">{% trans 'Pay' %}</a>
                    {# MARK AS PAID MODAL #}
                    {% modal_action_v2 invoice invoice.get_mark_as_paid_url invoice.get_mark_as_paid_message invoice.get_mark_as_paid_html_id %}
                {% endif %}

                {# MARK VOID #}
                {% if invoice.can_void %}
                    <a onclick="djLedger.toggleModal('{{ invoice.get_mark_as_void_html_id }}')"
                       id="{{ invoice.get_mark_as_void_html_id }}-button"
                       class="card-footer-item has-text-info has-text-centered has-text-danger">{% trans 'Void' %}</a>
                    {# MARK AS PAID MODAL #}
                    {% modal_action_v2 invoice invoice.get_mark_as_void_url invoice.get_mark_as_void_message invoice.get_mark_as_void_html_id %}
                {% endif %}

                {# MARK CANCELED #}
                {% if invoice.can_cancel %}
                    <a onclick="djLedger.toggleModal('{{ invoice.get_mark_as_canceled_html_id }}')"
                       id="{{ invoice.get_mark_as_canceled_html_id }}-button"
                       class="card-footer-item has-text-info has-text-centered has-text-danger">{% trans 'Cancel' %}</a>
                    {# MARK AS PAID MODAL #}
                    {% modal_action_v2 invoice invoice.get_mark_as_canceled_url invoice.get_mark_as_canceled_message invoice.get_mark_as_canceled_html_id %}
                {% endif %}


            </footer>
        </div>

    {% endif %}
{% else %}
    <div class="box has-text-centered">
        <a href="{% url 'django_ledger:invoice-create' entity_slug=entity_slug %}">
            <span class="icon is-large has-text-grey">{% icon "ic:baseline-add-circle-outline" 48 %}</span></a>
        <h2 class="is-size-3 has-text-grey">{% trans 'New Invoice' %}</h2>
    </div>
{% endif %}

django-ledger/django_ledger/templates/django_ledger/includes/card_markdown.html
{% load trans from i18n %}
{% load django_ledger %}

{% if style == 'card_1' %}
    <div class="card">
        <div class="card-header">
            <div class="card-header-title">
                <h1 class="is-size-3 has-text-weight-light">{% if title %}{{ title }}{% else %}
                    {% trans 'Notes' %}
                {% endif %}</h1>
            </div>
        </div>
        <div class="card-content">
            <div class="content">
                {% if notes_html %}
                    {% autoescape off %}
                        {{ notes_html | safe }}
                    {% endautoescape %}
                {% else %}
                    <p>{% trans 'No available notes to display...' %}</p>
                {% endif %}
            </div>
        </div>
    </div>
{% endif %}